import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtemp,readFile,mkdir,writeFile,cp} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import http from 'node:http';
import {chromium,devices} from '@playwright/test';import {browserOptions} from './browser-options.mjs';
const root=await mkdtemp(path.join(tmpdir(),'hijoshoku-marketing-'));const pub=path.join(root,'public');const drafts=path.join(root,'drafts');const artifacts=process.env.ARTIFACT_DIR||path.join(root,'evidence');await mkdir(artifacts,{recursive:true});
const hugo=process.env.HUGO_BIN||'hugo';
execFileSync(hugo,['--panicOnWarning','--minify','--destination',pub],{stdio:'inherit'});
execFileSync(hugo,['--panicOnWarning','--minify','--buildDrafts','--destination',drafts],{stdio:'inherit'});
const route='/ranking/';let serving=pub;
const server=http.createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p.endsWith('/'))p+='index.html';const f=path.resolve(serving,'.'+p);assert(f.startsWith(serving+path.sep));const bytes=await readFile(f);const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'}).end(bytes);}catch{res.writeHead(404).end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const b=await chromium.launch(browserOptions());const checks=[];
try{for(const device of [{name:'mobile',...devices['iPhone 13']},{name:'desktop',viewport:{width:1440,height:1000}}]){const {name,...options}=device;const c=await b.newContext(options);const page=await c.newPage();await c.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.goto(base+route);await page.screenshot({path:path.join(artifacts,`${name}-ranking-first.png`)});const links=page.locator('.article-content a[data-commerce="rakuten"]');assert.equal(await links.count(),3);assert(await links.evaluateAll(as=>as.every(a=>!a.closest('details:not([open])'))),'ranking: all sales links must be available without opening a disclosure');await links.first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,`${name}-ranking-action.png`)});checks.push(`${name}: ranking sales links visible`);await c.close();}
if(process.env.RANKING_ONLY!=='1'){
 const routes=['/posts/emergency-food-set-check/','/posts/emergency-food-side-dishes/'];
 const home=await readFile(path.join(pub,'index.html'),'utf8');
 for(const r of routes){assert.equal((await fetch(base+r)).status,200,'Approved article must be in normal build');assert((await readFile(path.join(pub,'sitemap.xml'),'utf8')).includes(r),'Published article must be in sitemap');assert(home.includes(r),'Published article must be reachable from home');}
 // Keep a real draft-exclusion regression even after publishing this batch.
 const fixture=path.join(root,'content-fixture');await cp('content',fixture,{recursive:true});const source=path.join(fixture,'posts/emergency-food-set-check.md');const original=await readFile(source,'utf8');assert(/^draft: false$/m.test(original));await writeFile(source,original.replace(/^draft: false$/m,'draft: true'));const draftNormal=path.join(root,'fixture-normal');const draftIncluded=path.join(root,'fixture-drafts');execFileSync(hugo,['--contentDir',fixture,'--destination',draftNormal,'--panicOnWarning'],{stdio:'inherit'});await assert.rejects(readFile(path.join(draftNormal,'posts/emergency-food-set-check/index.html')));assert(!(await readFile(path.join(draftNormal,'sitemap.xml'),'utf8')).includes(routes[0]));execFileSync(hugo,['--contentDir',fixture,'--destination',draftIncluded,'--buildDrafts','--panicOnWarning'],{stdio:'inherit'});assert((await readFile(path.join(draftIncluded,'posts/emergency-food-set-check/index.html'),'utf8')).includes('CY'));checks.push('normal build omits explicit draft fixture; buildDrafts includes it');
 serving=pub;
 for(const device of [{name:'mobile',...devices['iPhone 13']},{name:'desktop',viewport:{width:1440,height:1000}}]){const {name,...options}=device;const c=await b.newContext(options);const page=await c.newPage();const outbound=[];await c.route('**/*',r=>{if(new URL(r.request().url()).origin===base)return r.continue();outbound.push(new URL(r.request().url()).hostname);return r.abort();});
 for(const r of routes){const response=await page.goto(base+r);assert.equal(response.status(),200);assert.equal(await page.locator('h1').count(),1,JSON.stringify(await page.locator('h1').allTextContents()));assert.equal(await page.locator('.article-header .article-jump').count(),1,'new article needs the existing header jump before the cover photo');const jumpBox=await page.locator('.article-header .article-jump').boundingBox();assert(jumpBox.y+jumpBox.height<=page.viewportSize().height,'next action must fit the first viewport');assert.equal(await page.locator('.article-content [data-testid="next-action"]').count(),1,'one next action');assert.equal(await page.locator('.article-references').count(),1);assert(await page.locator('.article-references li').count()>=2);const registry=JSON.parse(await readFile('data/article-evidence.json','utf8')).articles;const ledger=JSON.parse(await readFile('docs/sources/ledger.json','utf8'));const key=r.includes('set-check')?'set_check':'side_dishes';const latest=ledger.sources.filter(s=>registry[key].source_ids.includes(s.id)).map(s=>s.accessed).sort().at(-1);assert((await page.locator('.article-references p').innerText()).includes(latest),'article reference date must use its own latest source');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const slug=r.split('/').filter(Boolean).at(-1);await page.screenshot({path:path.join(artifacts,`${name}-${slug}-first.png`)});for(const img of await page.locator('img:not(.product-photo img)').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(x=>x.decode());assert(await img.evaluate(x=>x.naturalWidth>0&&x.alt.length>0));}for(const a of await page.locator('.article-content a[href^="/"]').all()){const href=await a.getAttribute('href');const target=href.split('#')[0]||r;assert.equal((await fetch(base+target)).status,200,`Missing internal target ${href}`);}await page.locator('.article-content [data-testid="next-action"]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,`${name}-${slug}-action.png`)});await page.screenshot({path:path.join(artifacts,`${name}-${slug}-full.png`),fullPage:true});checks.push(`${name}: ${r} published, image, references, next action, internal links`);}
 assert(!outbound.some(h=>/google-analytics|googletagmanager/.test(h)),'No analytics in local preview');await c.close();}
}
await writeFile(path.join(artifacts,'marketing-sprint-result.json'),JSON.stringify({status:'PASS',checks,pub,drafts,artifacts},null,2));console.log(JSON.stringify({status:'PASS',checks,pub,drafts,artifacts},null,2));}finally{await b.close();await new Promise(r=>server.close(r));}
